services:
  - type: web
    name: auction-system
    env: docker
    plan: starter
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
    buildCommand: docker build -f deployment/Dockerfile -t auction-system .
    startCommand: docker run -p $PORT:3001 auction-system